// Generated by CoffeeScript 1.5.0
(function() {
  var $, BUY_BUTTON, CART_INDICATOR, PRODUCTS, SHOP, STYLE, _getJSONFromCookie, initAddToCartButtons, initCart, initCheckoutButton, renderCartList, renderCartQuantity, _serializeCartToUrl, renderCartList,
    __slice = [].slice;

  $ = jQuery;

  $.shopify = {};

  $.shopify.fn = {};

  $.fn.shopify = function() {
    var args, method;
    method = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return $.shopify.fn[method].apply(this, args);
  };

  PRODUCTS = {};

  SHOP = "";

  CART_INDICATOR = "";

  BUY_BUTTON = "";

  STYLE = "";

  initAddToCartButtons = function() {
    $("[data-add-product]").on('click', function() {
      return $(this).trigger('add-product');
    });
    return $("#shopify-widgets").on('add-product', function(event) {
      var handle, product;
      handle = $(event.target).parents("[data-product]").data("product");
      product = $.shopify.requestDataFromHandle(handle);
      return $.shopify.addProductToCart(product);
    });
  };

  initCheckoutButton = function() {
    return $("[data-checkout]").on('click', function() {
      return _serializeCartToUrl();
    });
  };

  initCart = function() {
    renderCartQuantity();
    return renderCartList();
  };

  renderCartQuantity = function() {
    var count, key, products, quantities, value;
    if (products = _getJSONFromCookie()) {
      quantities = (function() {
        var _results;
        _results = [];
        for (key in products) {
          value = products[key];
          _results.push(value);
        }
        return _results;
      })();
      count = quantities.reduce(function(t, s) {
        return t + s;
      });
      return $("[data-cart-length]").html("<span>(" + count + " items)</span>");
    } else {
      return $("[data-cart-length]").html("");
    }
  };

  renderCartList = function() {
    return renderCartList();
  };

  renderCartList = function() {
    var html, key, products, title, value;
    if (products = _getJSONFromCookie()) {
      html = (function() {
        var _results;
        _results = [];
        for (key in products) {
          value = products[key];
          title = $.shopify.requestDataFromHandle(key).title;
          _results.push("<li>" + title + " (" + value + ")</li>");
        }
        return _results;
      })();
      $("#cart-empty").addClass('hidden');
      $("#cart-items").removeClass('hidden');
      return $("#cart-items").html(html);
    } else {
      return $("#cart-items").html("");
    }
  };

  _getJSONFromCookie = function() {
    var cookie, products;
    cookie = $.cookie('cart');
    if (cookie) {
      return products = JSON.parse(cookie);
    }
  };

  _serializeCartToUrl = function() {
    var id, key, product, products, quantities, value;
    if (products = _getJSONFromCookie()) {
      quantities = (function() {
        var _results;
        _results = [];
        for (key in products) {
          value = products[key];
          product = $.shopify.requestDataFromHandle(key);
          id = product.variants[0].id;
          _results.push("" + id + ":" + value);
        }
        return _results;
      })();
      return window.location.replace("http://dundas.myshopify.com/cart/" + (quantities.join(',')));
    }
  };

  window.Cart = (function() {

    function Cart() {}

    Cart.prototype.addItem = function(handle) {};

    Cart.prototype.removeItem = function(handle) {};

    return Cart;

  })();

  window.Product = (function() {

    function Product() {}

    Product.prototype.render = function() {
      var node;
      node = $(".shopify-widget-product[data-product='" + this.handle + "']");
      node.find("[data-product-title]").text(this.title);
      return node.find("[data-product-body-html]").html(this.body_html);
    };

    return Product;

  })();

  $.shopify.addProductToCart = function(product) {
    var cart, cookie;
    $("#cart-empty").addClass('hidden');
    $("#cart-items").removeClass('hidden');
    renderCartList();
    cart = (cookie = $.cookie('cart')) ? JSON.parse(cookie) : {};
    cart[product.handle] = cart[product.handle] ? cart[product.handle] + 1 : 1;
    $.cookie('cart', JSON.stringify(cart));
    return renderCartQuantity();
  };

  $.shopify.scanDOMForProducts = function() {
    return $(".shopify-widget-product").map(function(_, node) {
      return $(node).data("product");
    });
  };

  $.shopify.requestDataFromHandle = function(handle, callback) {
    var product;
    if (product = PRODUCTS[handle]) {
      if (typeof callback === "function") {
        callback();
      }
      return product;
    } else {
      return $.ajax({
        url: "http://simpledomainsomg.com/products/" + handle + ".json",
        dataType: 'jsonp',
        success: function(response) {
          var key, value, _ref;
          product = new Product;
          _ref = response.product;
          for (key in _ref) {
            value = _ref[key];
            product[key] = value;
          }
          PRODUCTS[handle] = product;
          product.render();
          return typeof callback === "function" ? callback() : void 0;
        }
      });
    }
  };

  $.shopify.loadProducts = function(callback) {
    var finishedIDS, handles;
    handles = $.shopify.scanDOMForProducts();
    finishedIDS = [];
    return handles.map(function(_, handle) {
      return $.shopify.requestDataFromHandle(handle, function() {
        finishedIDS.push(handle);
        if (handles.length === finishedIDS.length) {
          return callback();
        }
      });
    });
  };

  $.shopify.start = function(options) {
    if (options == null) {
      options = {};
    }
    SHOP = options.shop;
    CART_INDICATOR = options.cart_indicator;
    BUY_BUTTON = options.buy_button;
    STYLE = options.style;
    $.shopify.loadProducts(function() {
      renderCartList();
      initAddToCartButtons();
      initCart();
      return initCheckoutButton();
    });
    return this;
  };

  window.PRODUCTS = PRODUCTS;

}).call(this);
